---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/freelancers":
    get:
      summary: list freelancers
      tags:
      - Freelancers
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                      example: Letty Fadel II
                    photo:
                      type: string
                      example: http://smitham-prosacco.name/yuri
                      pattern: "^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)$"
                    details:
                      type: string
                      example: Et molestiae quidem. Repellendus maxime dolor. Nostrum
                        magni illum.
                    fee:
                      type: integer
                      example: 50
                    location:
                      type: string
                      example: 475 Latonia Mall
                    created_at:
                      type: string
                      format: datetime
                      example: '2022-12-16'
                    updated_at:
                      type: string
                      format: datetime
                      example: '2022-12-26'
    post:
      summary: create freelancer
      tags:
      - Create freelancer
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Sammy Erdman DO
                photo:
                  type: string
                  example: http://mclaughlin.info/arlena
                  pattern: "^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)$"
                details:
                  type: string
                  example: Et commodi veniam. Facilis ut architecto. Voluptatem molestias
                    omnis.
                fee:
                  type: integer
                  example: 81
                location:
                  type: string
                  example: 282 Timmy Divide
              required:
              - name
              - photo
              - details
              - fee
              - location
  "/api/v1/freelancers/{id}":
    get:
      summary: show freelancer
      tags:
      - Freelancer
      parameters:
      - name: id
        in: path
        description: id
        default: 1
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                    example: Lucius Wisozk
                  photo:
                    type: string
                    example: http://kunze-moen.info/aracelis
                    pattern: "^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)$"
                  details:
                    type: string
                    example: Animi placeat fugit. Autem doloribus in. Similique est
                      quisquam.
                  fee:
                    type: integer
                    example: 84
                  location:
                    type: string
                    example: 8865 Fritsch Summit
                  created_at:
                    type: string
                    format: datetime
                    example: '2022-12-16'
                  updated_at:
                    type: string
                    format: datetime
                    example: '2022-12-19'
                required:
                - id
                - name
                - photo
                - details
                - fee
                - location
        '404':
          description: freelancer not found
    delete:
      summary: delete freelancer
      tags:
      - Delete Freelancer
      parameters:
      - name: id
        in: path
        description: id
        default: 0
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/reservations":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      tags:
      - Reservations
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    appointment_date:
                      type: string
                      format: datetime
                      example: '2023-01-07'
                    freelancer_id:
                      type: integer
                      example: 1
                    user_id:
                      type: integer
                      example: user_id
                    created_at:
                      type: string
                      format: datetime
                      example: '2022-12-17'
                    updated_at:
                      type: string
                      format: datetime
                      example: '2022-12-16'
        '404':
          description: user not found
    post:
      summary: create reservation
      tags:
      - Reservation
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                appointment_date:
                  type: string
                  format: datetime
                  example: '2023-01-05'
                freelancer_id:
                  type: integer
                  example: 2
              required:
              - appointment_date
              - freelancer_id
  "/api/v1/users/{user_id}/reservations/new":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: new reservation
      tags:
      - Create reservation
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                appointment_date:
                  type: string
                  format: datetime
                  example: '2023-01-17'
                freelancer_id:
                  type: integer
                  example: 3
              required:
              - appointment_date
              - freelancer_id
  "/api/v1/specializations":
    get:
      summary: list specializations
      tags:
      - Specializations
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                      example: The Hon. Jarred Berge
                    created_at:
                      type: string
                      format: datetime
                      example: '2022-12-24'
                    updated_at:
                      type: string
                      format: datetime
                      example: '2022-12-19'
    post:
      summary: create specialization
      tags:
      - Create specialization
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Dreama Gutmann
              required:
              - name
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: gofreelancer.up.railway.app/
